### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by KevinJue** [mattconnolly/ZipArchive#33]
Hello,

On 'pod update' I have detect some error on miniunz.h and minizip.h. We trying to call files not find (direct.h and io.h)
```
ifdef unix
 include <unistd.h>
 include <utime.h>
 include <sys/stat.h>
else
 include <direct.h>
 include <io.h>
endif
```

I solved the problem by removing both include but regularly i'm doing pod update so if i get this error each time ... it could be a problem 
can you fix it ?

**Comment by goktugaral** [comment]
Same issue!

**Comment by mattconnolly** [comment]
I just made a brand new Xcode project with a podfile like this:

``` rb
platform :ios
pod "ZipArchive"
```

Ran pod install and then opened my workspace and could start using ZipArchive with no troubles.
