### ISSUE TITLE
UnzipOpenFile doesn't work

### ISSUE THREAD

**Issue by Borys216307** [mattconnolly/ZipArchive#45]
I have used ZipArchive to zip and unzip some file, but UnzipOpenFile returns nil.
Please help me on this.

ZipArchive\* za = [[ZipArchive alloc] init];

```
                if([[NSFileManager defaultManager] fileExistsAtPath:zipFolder]) {
                    NSLog(@"File exists at path: %@", zipFolder);
                } else {
                    NSLog(@"File does not exists at path: %@", zipFolder);
                }

                if( [za UnzipOpenFile: zipFolder] ) {
                    if( [za UnzipFileTo:outputFolder overWrite:YES] != NO ) {
                        NSLog(@"Pics : unzip successfully");

                        [[NSNotificationCenter defaultCenter] postNotificationName:kNotificationArticleLoadedFromiCloud object:nil];
                    }
                    [za UnzipCloseFile];
                }
```

**Comment by TechD-Robin** [comment]
maybe your zipFolder need with a zip filename like this : 

NSString *documentsDirectory = [NSHomeDirectory() stringByAppendingPathComponent:@"Documents"];
NSString *zipPath = [documentsDirectory stringByAppendingPathComponent:[NSString stringWithFormat:@"zipFile.zip"]];
if ( [za unzipOpenFile: zipPath] ) {
//...
}

----
hope it helps u.
