### ISSUE TITLE
ZipArchive.podspec need update 

### ISSUE THREAD

**Issue by liuyuqiang** [mattconnolly/ZipArchive#48]
s.source       = { :git => 'https://github.com/mattconnolly/ZipArchive.git', :tag => '1.4.0' } 

need change 

 s.source       = { :git => 'https://github.com/mattconnolly/ZipArchive.git', :tag => 'v1.4.0' }

?
error is 
[!] /usr/bin/git fetch origin tags/1.4.0 2>&1

fatal: Couldn't find remote ref tags/1.4.0

fatal: The remote end hung up unexpectedly

**Comment by mattconnolly** [comment]
Sorry. I just pushed a 1.4.0 tag so the current spec will be fine.
