### ISSUE TITLE
getZipFileContents does not produce the same filenames as UnzipFileTo:overWrite: 

### ISSUE THREAD

**Issue by depinette** [mattconnolly/ZipArchive#57]
When filenames in the zip file contain non ASCII characters (e.g. ö) , getZipFileContents does not give the same filename as those created by unzipFileTo.
It seems to be caused by the following line:
NSString * strPath = [NSString stringWithCString:filename encoding:**NSASCIIStringEncoding**];

I think it should be:
NSString * strPath = [NSString stringWithCString:filename encoding:**self.stringEncoding**];

**Comment by mattconnolly** [comment]
Well spotted.
