### ISSUE TITLE
"direct.h" file not found 

### ISSUE THREAD

**Issue by songbaoqiang** [mattconnolly/ZipArchive#66]

**Comment by hemang-azilen** [comment]
@songbaoqiang, did you find any solution for this?

**Comment by songbaoqiang** [comment]
https://github.com/ZipArchive/ZipArchive

**Comment by hemang-azilen** [comment]
Is it different ? What's the difference between these two?

**Comment by songbaoqiang** [comment]
i don't know.It works for me.
